openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  description: Backend for managing users and their contacts.
tags:
  - name: Auth
    description: Endpoints for registration, login, refresh, logout
  - name: Contacts
    description: CRUD operations on contacts
servers:
  - url: https://app-contacts-swagger.onrender.com
  - url: http://localhost:3000
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml#/post'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml#/post'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml#/post'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml#/post'

  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get-contacts.yaml#/get'
    post:
      $ref: '../swagger/paths/contacts/post-contact.yaml#/post'

  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{contactId}/get.yaml#/get'
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml#/patch'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml#/delete'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    ContactInput:
      $ref: '../swagger/components/schemas/contact-input.yaml#/ContactInput'
    Contact:
      $ref: '../swagger/components/schemas/contact.yaml#/Contact'
    Error:
      $ref: '../swagger/components/schemas/error.yaml#/Error'
