openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  description: Backend for managing users and their contacts.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3000
  - url: https://<your-deployed-url>

tags:
  - name: Auth
    description: Endpoints for registration, login, refresh and logout
  - name: Contacts
    description: CRUD operations on contacts

paths:
  /auth/register:
    $ref: '../swagger/paths/auth/register.yaml'

  /auth/login:
    $ref: '../swagger/paths/auth/login.yaml'

  /auth/refresh:
    $ref: '../swagger/paths/auth/refresh.yaml'

  /auth/logout:
    $ref: '../swagger/paths/auth/logout.yaml'

  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get-contacts.yaml#/get'
    post:
      $ref: '../swagger/paths/contacts/post-contact.yaml#/post'

  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{contactId}/get.yaml#/get'
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml#/patch'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml#/delete'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    ContactInput:
      $ref: '../swagger/components/schemas/contact-input.yaml#/ContactInput'
    Contact:
      $ref: '../swagger/components/schemas/contact.yaml#/Contact'
    Error:
      $ref: '../swagger/components/schemas/error.yaml#/Error'
